# Análisis de Regresión Lineal - Proyecto Pokémon

Este notebook aplica un modelo de regresión lineal para predecir el HP de los Pokémon utilizando variables como ataque, defensa y velocidad. Se utilizan técnicas de aprendizaje supervisado y se evalúa el modelo mediante métricas como MSE, MAE y R2.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("Librerías cargadas correctamente")

Librerías cargadas correctamente

In [9]:
df = pd.read_csv("../data/pokemon.csv")
df.head()

,id,nombre,es_default,altura,peso,experiencia_base,tipos,habilidades,habilidades_ocultas,hp,...,es_legendario,es_mitico,tasa_captura,felicidad_base,habitat,generacion,cadena_evolucion_url,sprite_frente,sprite_shiny,fecha_extraccion
0,1,bulbasaur,True,7,69,64,"grass, poison","overgrow, chlorophyll",chlorophyll,45,...,False,False,45,70,grassland,generation-i,https://pokeapi.co/api/v2/evolution-chain/1/,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-02-26T06:23:48.194887
1,2,ivysaur,True,10,130,142,"grass, poison","overgrow, chlorophyll",chlorophyll,60,...,False,False,45,70,grassland,generation-i,https://pokeapi.co/api/v2/evolution-chain/1/,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-02-26T06:23:49.122827
2,3,venusaur,True,20,1000,236,"grass, poison","overgrow, chlorophyll",chlorophyll,80,...,False,False,45,70,grassland,generation-i,https://pokeapi.co/api/v2/evolution-chain/1/,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-02-26T06:23:50.155032
3,4,charmander,True,6,85,62,fire,"blaze, solar-power",solar-power,39,...,False,False,45,70,mountain,generation-i,https://pokeapi.co/api/v2/evolution-chain/2/,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-02-26T06:23:51.167751
4,5,charmeleon,True,11,190,142,fire,"blaze, solar-power",solar-power,58,...,False,False,45,70,mountain,generation-i,https://pokeapi.co/api/v2/evolution-chain/2/,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-02-26T06:23:52.195388

In [10]:
len(df)

150

In [12]:
import pandas as pd
from sqlalchemy import create_engine

DB_HOST = "aws-1-us-east-1.pooler.supabase.com"
DB_PORT = "5432"
DB_USER = "postgres.cpgbhxqfiraedevzgbgk"
DB_PASSWORD = "Lucario2026"
DB_NAME = "postgres"

DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}?sslmode=require"

engine = create_engine(DATABASE_URL)

df = pd.read_sql("SELECT * FROM pokemon ORDER BY id", engine)

print(len(df))
df.head()

1000

,id,nombre,altura,peso,experiencia_base,tipos,habilidades,habilidades_ocultas,hp,ataque,...,es_legendario,es_mitico,tasa_captura,felicidad_base,habitat,generacion,descripcion,sprite_frente,sprite_shiny,fecha_extraccion
0,1,bulbasaur,7,69,64,"grass, poison","overgrow, chlorophyll",chlorophyll,45,49,...,False,False,45.0,70.0,grassland,generation-i,Una rara semilla le fue plantada en el lomo al...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-03-28 13:07:37.418219
1,2,ivysaur,10,130,142,"grass, poison","overgrow, chlorophyll",chlorophyll,60,62,...,False,False,45.0,70.0,grassland,generation-i,Este Pokémon tiene un bulbo en el lomo. Dicen ...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-03-28 13:07:40.178481
2,3,venusaur,20,1000,236,"grass, poison","overgrow, chlorophyll",chlorophyll,80,82,...,False,False,45.0,70.0,grassland,generation-i,Llena su cuerpo de energía con los rayos solar...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-03-28 13:07:41.177698
3,4,charmander,6,85,62,fire,"blaze, solar-power",solar-power,39,52,...,False,False,45.0,70.0,mountain,generation-i,La llama de su cola indica la fuerza vital de ...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-03-28 13:07:42.045424
4,5,charmeleon,11,190,142,fire,"blaze, solar-power",solar-power,58,64,...,False,False,45.0,70.0,mountain,generation-i,Suele usar la cola para derribar a su rival. C...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,2026-03-28 13:07:42.914483

In [13]:
X = df[['ataque', 'defensa', 'velocidad']]
y = df['hp']

print("Variables listas")

Variables listas

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

modelo = LinearRegression()

modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print("Modelo entrenado correctamente")

Modelo entrenado correctamente

In [15]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("MAE:", mae)
print("R2:", r2)

MSE: 489.7022586857043
MAE: 15.59268411064675
R2: 0.299681406297169